env: "local" # local, dev, prod
# storage_path: "./storage.db"
http_server:
  address: "0.0.0.0:8000"
  timeout: 10s
  idle_timeout: 60s
  user: "abdu1bari"
  password: "7721"

database:
  host : "127.0.0.1"
  port : "5432"
  user : "postgres"
  password : "postgres"
  dbname : "postgres"

development:
  driver: postgres
  open: user=postgres password=postgres dbname=postgres host=127.0.0.1 port=5432 sslmode=disable

  # goose -dir ./migrations postgres "user=postgres password=postgres dbname=postgres host=127.0.0.1 port=5432 sslmode=disable" down
  # export PATH=$PATH:$(go env GOPATH)/bin